[book]
authors = []
multilingual = false
title = "Now is the Time"
src = "src"
[output.html]
additional-js = [
    "counter.js"
]

[build]
build-dir = "docs"
create-missing = true

[preprocessor.presentation-preprocessor]